### PR TITLE
Create a format descriptor in dimensions.json

### LINKED ISSUE #52: Place a format descriptor in the output
As part of [Archive ops issue 607](https://github.com/buda-base/archive-ops/issues/607) @eroux makes a case for an image type descriptor going into the output of volume_manifest_builder.
The fix for this issue will map image types into a controlled dictionary that IIFPRES uses to determine the image type.

At @eroux request, the implementation was updated to only emit the image format discovered from the image when that image format does not match the file name extension. The mappings of image formats to file name extensions is coded as:

Image Format|File suffixes - case insensitive
---|---
JPEG|jpg, jpeg
TIFF|tiff, tif

### PR DESCRIPTION
**Pull request by jimk-bdrc**
Fixes #52 byt adding a descriptor named "format" to each node. The values of format are the ones found in the `PIL.features.pilinfo(suppoprted_formats=True)` command:

....
--------------------------------------------------------------------
BLP
Extensions: .blp
Features: open
--------------------------------------------------------------------
BMP image/bmp
Extensions: .bmp
Features: open, save
--------------------------------------------------------------------
BUFR
Extensions: .bufr
Features: open, save
--------------------------------------------------------------------
CUR
Extensions: .cur
Features: open
--------------------------------------------------------------------
DCX
Extensions: .dcx
Features: open
--------------------------------------------------------------------
DDS
Extensions: .dds
Features: open, save
--------------------------------------------------------------------
DIB image/bmp
Extensions: .dib
Features: open, save
--------------------------------------------------------------------
EPS application/postscript
Extensions: .eps, .ps
Features: open, save
--------------------------------------------------------------------
FITS
Extensions: .fit, .fits
Features: open, save
--------------------------------------------------------------------
FLI
Extensions: .flc, .fli
Features: open
--------------------------------------------------------------------
FTEX
Extensions: .ftc, .ftu
Features: open
--------------------------------------------------------------------
GBR
Extensions: .gbr
Features: open
--------------------------------------------------------------------
GIF image/gif
Extensions: .gif
Features: open, save, save_all
--------------------------------------------------------------------
GRIB
Extensions: .grib
Features: open, save
--------------------------------------------------------------------
HDF5
Extensions: .h5, .hdf
Features: open, save
--------------------------------------------------------------------
ICNS image/icns
Extensions: .icns
Features: open, save
--------------------------------------------------------------------
ICO image/x-icon
Extensions: .ico
Features: open, save
--------------------------------------------------------------------
IM
Extensions: .im
Features: open, save
--------------------------------------------------------------------
IMT
Features: open
--------------------------------------------------------------------
IPTC
Extensions: .iim
Features: open
--------------------------------------------------------------------
JPEG image/jpeg
Extensions: .jfif, .jpe, .jpeg, .jpg
Features: open, save
--------------------------------------------------------------------
JPEG2000 image/jp2
Extensions: .j2c, .j2k, .jp2, .jpc, .jpf, .jpx
Features: open, save
--------------------------------------------------------------------
MCIDAS
Features: open
--------------------------------------------------------------------
MPEG video/mpeg
Extensions: .mpeg, .mpg
Features: open
--------------------------------------------------------------------
MSP
Extensions: .msp
Features: open, save, decode
--------------------------------------------------------------------
PCD
Extensions: .pcd
Features: open
--------------------------------------------------------------------
PCX image/x-pcx
Extensions: .pcx
Features: open, save
--------------------------------------------------------------------
PIXAR
Extensions: .pxr
Features: open
--------------------------------------------------------------------
PNG image/png
Extensions: .apng, .png
Features: open, save, save_all
--------------------------------------------------------------------
PPM image/x-portable-anymap
Extensions: .pbm, .pgm, .pnm, .ppm
Features: open, save
--------------------------------------------------------------------
PSD image/vnd.adobe.photoshop
Extensions: .psd
Features: open
--------------------------------------------------------------------
SGI image/sgi
Extensions: .bw, .rgb, .rgba, .sgi
Features: open, save
--------------------------------------------------------------------
SPIDER
Features: open, save
--------------------------------------------------------------------
SUN
Extensions: .ras
Features: open
--------------------------------------------------------------------
TGA image/x-tga
Extensions: .icb, .tga, .vda, .vst
Features: open, save
--------------------------------------------------------------------
TIFF image/tiff
Extensions: .tif, .tiff
Features: open, save, save_all
--------------------------------------------------------------------
WEBP image/webp
Extensions: .webp
Features: open, save, save_all
--------------------------------------------------------------------
WMF
Extensions: .emf, .wmf
Features: open, save
--------------------------------------------------------------------
XBM image/xbm
Extensions: .xbm
Features: open, save
--------------------------------------------------------------------
XPM image/xpm
Extensions: .xpm
Features: open
--------------------------------------------------------------------
XVTHUMB
Features: open
---------

### CODE REVIEW

**Comment by eroux** [comment]
is it possible to have the format in the data only in cases where it doesn't match the format that can be expected from the extension?

**Comment by jimk-bdrc** [comment]
> is it possible to have the format in the data only in cases where it doesn't match the format that can be expected from the extension?

It's possible, but what is the value to you? BUDA would have to write code that's like:

```
if (format not present in manifest) {
     process for (specially maintained list of file types to file formats mapping)
}
else {
     process for format in manifest
}

and I would have to maintain the exact inverse code:

if ( inspected file format != (specially maintained list of file types to format mapping hash) ) {
    emit inspected file format
}
```

That leaves both of us to maintain independent, equal lists of special file types, that we'd have to coordinate on (unless you want to write a service API to send them.) And what happens when we find some rare, or new file type?  

It just seems like a maintenance headache that leads to less reliable code, although the idea of LDS exposing some of its needs (file formats to extensions mapping)  makes some sense to me, because then audit tool could use it too, and emit warnings or errors in that case.

**Comment by eroux** [comment]
we only have two formats, tiff and jpg (I don't have a path for other file types in the server and I already handle the extensions). I don't really see the maintenance of the list of 4 extensions (`tif`, `tiff`, `jpg` and `jpeg`) as a headache... I think it's quite important for the audit tool to check that, independently of a web API that BUDA would provide. wdyt?

**Comment by jimk-bdrc** [comment]
Still don't like it, but if it's really important, I'll only include the format if it's different from the file type, as  you asked. Maybe in your code that reads this data, you could reference this issue's URL, so people will know where to look. You should see some changes checked in shortly.

**Comment by eroux** [comment]
thanks!

**Pull request merged**
